# Generated by Django 3.2.13 on 2022-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50, unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('ceo', models.CharField(max_length=20)),
                ('turnover', models.IntegerField()),
                ('website', models.CharField(max_length=50)),
                ('stockenlist', models.CharField(max_length=3)),
            ],
        ),
    ]
