# Generated by Django 3.2.13 on 2022-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='sdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
